### ISSUE TITLE
processor load reduction

### ISSUE THREAD

**Issue by danil1petrov** [sciboy12/Abs#2]
warp_pointer(x,y) uses many times with the same variable values. This causes a very high load on the processor. (50% for pentium n4200)
since i can't program, i couldn't write anything better
https://pastebin.com/RbaxGGRQ
values from the previous result of the cycle are checked and compared with the new values
now the load does not increase above 26%
This is much better, but still very heavy.

**Comment by danil1petrov** [comment]
of corse sorry for my English

**Comment by sciboy12** [comment]
As my code seems to have somewhat less lag, I've decided to implement your code alongside mine.
I've added a new option in the config section for this, as well an option to enable mouse buttons.

**Comment by danil1petrov** [comment]
Thank you very much! now works great on my laptop

**Comment by sciboy12** [comment]
You're welcome.
